<a href="https://colab.research.google.com/github/Fidel-Leanne/pyTorch/blob/master/pyTorchFundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

pyTorch intro

In [1]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

print(torch.__version__)

2.0.1+cu118


Introduction to Tensors:

Creating Tensors

In [2]:
# scalar

scalar= torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
#vector

vector= torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#MATRIX
MATRIX = torch.tensor([[8 , 0],
                      [7, 9]])

MATRIX


tensor([[8, 0],
        [7, 9]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([8, 0])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
#TENSOR
TENSOR = torch.tensor([[[5, 9 ,7],
                        [7, 8, 0],
                        [8, 9, 9]]])

TENSOR

tensor([[[5, 9, 7],
         [7, 8, 0],
         [8, 9, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

Random Tensors

'start with random numbers -> look at data->update random numbers -> look at data- update random numbers

In [15]:
# create a random tensor

random_tensor = torch.rand(7, 7)
random_tensor

tensor([[0.8882, 0.9629, 0.6354, 0.6159, 0.0807, 0.3926, 0.5068],
        [0.5514, 0.2998, 0.2308, 0.2099, 0.9512, 0.2565, 0.3505],
        [0.4129, 0.2526, 0.8608, 0.5481, 0.5659, 0.4203, 0.2908],
        [0.3228, 0.3061, 0.6930, 0.8356, 0.0911, 0.5380, 0.7162],
        [0.5008, 0.7398, 0.4430, 0.9723, 0.5589, 0.7678, 0.3387],
        [0.7877, 0.3886, 0.3666, 0.2055, 0.1429, 0.9976, 0.7938],
        [0.2200, 0.3268, 0.2347, 0.1997, 0.5953, 0.4054, 0.5160]])

In [16]:
random_tensor.ndim

2

In [17]:
#create a random tensor with similar shape to an image tensor

random_image_size_tensor= torch.rand(size =(222,223, 8))#height, width,color channel
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([222, 223, 8]), 3)

In [18]:
random_image_size_tensor

tensor([[[0.3284, 0.8104, 0.8171,  ..., 0.4542, 0.8880, 0.5592],
         [0.3937, 0.1687, 0.6964,  ..., 0.5922, 0.5919, 0.6497],
         [0.5716, 0.6429, 0.4308,  ..., 0.0271, 0.1290, 0.9555],
         ...,
         [0.8511, 0.4827, 0.6178,  ..., 0.5136, 0.1680, 0.3660],
         [0.3432, 0.0810, 0.2450,  ..., 0.0729, 0.1887, 0.3829],
         [0.7068, 0.3123, 0.3261,  ..., 0.9086, 0.5947, 0.4950]],

        [[0.8175, 0.3402, 0.1373,  ..., 0.5683, 0.7597, 0.3026],
         [0.2111, 0.2048, 0.7861,  ..., 0.3876, 0.3721, 0.0817],
         [0.2530, 0.8116, 0.6080,  ..., 0.9007, 0.4310, 0.6211],
         ...,
         [0.0988, 0.7653, 0.9835,  ..., 0.4746, 0.2796, 0.6689],
         [0.9461, 0.6682, 0.8474,  ..., 0.5745, 0.7899, 0.3444],
         [0.7189, 0.2748, 0.0298,  ..., 0.7125, 0.6586, 0.0335]],

        [[0.7679, 0.4052, 0.5889,  ..., 0.5210, 0.6354, 0.3399],
         [0.3469, 0.2441, 0.4460,  ..., 0.4858, 0.3397, 0.6837],
         [0.6741, 0.8167, 0.4268,  ..., 0.3297, 0.6495, 0.

In [19]:
#create a tensor of all zeros

zeros = torch.zeros(size=(7, 7))
zeros

tensor([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]])

In [20]:
#create a tensor of all ones

ones= torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
#use torch.range
torch.range(0, 10)

<ipython-input-21-a089c3bf7207>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [22]:
one_to_ten= torch.arange(start=0, end= 10000, step=100)
one_to_ten

tensor([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000, 1100,
        1200, 1300, 1400, 1500, 1600, 1700, 1800, 1900, 2000, 2100, 2200, 2300,
        2400, 2500, 2600, 2700, 2800, 2900, 3000, 3100, 3200, 3300, 3400, 3500,
        3600, 3700, 3800, 3900, 4000, 4100, 4200, 4300, 4400, 4500, 4600, 4700,
        4800, 4900, 5000, 5100, 5200, 5300, 5400, 5500, 5600, 5700, 5800, 5900,
        6000, 6100, 6200, 6300, 6400, 6500, 6600, 6700, 6800, 6900, 7000, 7100,
        7200, 7300, 7400, 7500, 7600, 7700, 7800, 7900, 8000, 8100, 8200, 8300,
        8400, 8500, 8600, 8700, 8800, 8900, 9000, 9100, 9200, 9300, 9400, 9500,
        9600, 9700, 9800, 9900])

In [23]:
#creating tensors like

ten_zeros= torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0])

TENSOR DATATYPES

Note ❎Tensor datatypes are one of the 3 big issues you will run into with PyTorch and deep learning

1. Tensors not the right datatype
2. Tensors not the right shape
3. tensors not on the right devices

In [24]:
float_32_tensor= torch.tensor([3.0, 6.0, 7.0],
                              dtype=torch.float32,
                              device= None,
                              requires_grad=False
                              )

float_32_tensor

tensor([3., 6., 7.])

In [25]:
float_16_tensor= float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 7.], dtype=torch.float16)

In [26]:
float_32_tensor*float_16_tensor

tensor([ 9., 36., 49.])

In [27]:
int_32_tensor= torch.tensor([3, 6, 9],
                            dtype= torch.long)
int_32_tensor

tensor([3, 6, 9])

In [28]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 63.])

In [29]:
float_32_tensor.shape

torch.Size([3])

GETTING INFORMATION FROM TENSORS

In [30]:
some_tensor= torch.rand(5, 7)
some_tensor

tensor([[0.1902, 0.9525, 0.3161, 0.7942, 0.7200, 0.6685, 0.6451],
        [0.7412, 0.0298, 0.7904, 0.0891, 0.6905, 0.2464, 0.4193],
        [0.5155, 0.9149, 0.7861, 0.9954, 0.7756, 0.7719, 0.5697],
        [0.7154, 0.0712, 0.2413, 0.3361, 0.6007, 0.8038, 0.1144],
        [0.5375, 0.3212, 0.2681, 0.3936, 0.6717, 0.4483, 0.7149]])

In [31]:
print(some_tensor)
print(f"Datatype is {some_tensor.dtype}"  )
print(f"shape is {some_tensor.shape}" )
print(f"device is {some_tensor.device}" )



tensor([[0.1902, 0.9525, 0.3161, 0.7942, 0.7200, 0.6685, 0.6451],
        [0.7412, 0.0298, 0.7904, 0.0891, 0.6905, 0.2464, 0.4193],
        [0.5155, 0.9149, 0.7861, 0.9954, 0.7756, 0.7719, 0.5697],
        [0.7154, 0.0712, 0.2413, 0.3361, 0.6007, 0.8038, 0.1144],
        [0.5375, 0.3212, 0.2681, 0.3936, 0.6717, 0.4483, 0.7149]])
Datatype is torch.float32
shape is torch.Size([5, 7])
device is cpu


MANIPULATING TENSORS

one can multiply
divide
add
subtract
matrix multiplication

In [32]:
#create tensor

tensor= torch.tensor([7, 7, 8])
tensor+ 100

tensor([107, 107, 108])

In [33]:
tensor + 10

tensor([17, 17, 18])

In [34]:
tensor/2

tensor([3.5000, 3.5000, 4.0000])

In [35]:
tensor- 10

tensor([-3, -3, -2])

In [36]:
# using pytorch in built functions

print(torch.add(tensor, 20))
print(torch.mul(tensor, 2))
print(torch.sub(tensor, 2))
print(torch.div(tensor, 7))

tensor([27, 27, 28])
tensor([14, 14, 16])
tensor([5, 5, 6])
tensor([1.0000, 1.0000, 1.1429])


In [37]:
#MATRIX MULTIPLICATION/ dot product
print(tensor , "*", tensor)
print(f"equals: {tensor*tensor}")


tensor([7, 7, 8]) * tensor([7, 7, 8])
equals: tensor([49, 49, 64])


In [38]:
torch.matmul(tensor, tensor)

tensor(162)

One of the most common errors in deep learning: shape errors

In [39]:
#Shapes for matrix multiplication
tensor_A= torch.tensor([[1,4],
                       [7,7],
                       [8,9]])

tensor_B= torch.tensor([[1,8],
                        [8,0],
                        [9,8]])

torch.mm(tensor_A,tensor_B)

RuntimeError: ignored

In [40]:
tensor_B.shape , tensor_A.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

to fix the shape issues , we can multiply the shape of one of our tensors using a **transpose**

**Transpose **switches axis of one the tensors

In [41]:
tensor_A.T

tensor([[1, 7, 8],
        [4, 7, 9]])

In [42]:
torch.mm(tensor_A.T, tensor_B)

tensor([[129,  72],
        [141, 104]])

In [43]:
tensor_C=(tensor_B.T)
tensor_C.shape

torch.Size([2, 3])

TENSOR AGGREGATION