<a href="https://colab.research.google.com/github/Fidel-Leanne/pyTorch/blob/master/pyTorchFundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

pyTorch intro

In [52]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

print(torch.__version__)

2.0.1+cu118


Introduction to Tensors:

Creating Tensors

In [53]:
# scalar

scalar= torch.tensor(7)
scalar

tensor(7)

In [54]:
scalar.ndim

0

In [55]:
scalar.item()

7

In [56]:
#vector

vector= torch.tensor([7, 7])
vector

tensor([7, 7])

In [57]:
vector.ndim

1

In [58]:
vector.shape

torch.Size([2])

In [59]:
#MATRIX
MATRIX = torch.tensor([[8 , 0],
                      [7, 9]])

MATRIX


tensor([[8, 0],
        [7, 9]])

In [60]:
MATRIX.ndim

2

In [61]:
MATRIX[0]

tensor([8, 0])

In [62]:
MATRIX.shape

torch.Size([2, 2])

In [63]:
#TENSOR
TENSOR = torch.tensor([[[5, 9 ,7],
                        [7, 8, 0],
                        [8, 9, 9]]])

TENSOR

tensor([[[5, 9, 7],
         [7, 8, 0],
         [8, 9, 9]]])

In [64]:
TENSOR.ndim

3

In [65]:
TENSOR.shape

torch.Size([1, 3, 3])

Random Tensors

'start with random numbers -> look at data->update random numbers -> look at data- update random numbers

In [66]:
# create a random tensor

random_tensor = torch.rand(7, 7)
random_tensor

tensor([[0.5054, 0.4855, 0.3359, 0.1059, 0.2322, 0.0397, 0.3210],
        [0.6332, 0.3999, 0.2544, 0.9005, 0.8989, 0.9587, 0.2513],
        [0.6976, 0.0332, 0.3220, 0.5859, 0.4047, 0.0819, 0.9393],
        [0.4322, 0.9097, 0.6155, 0.9280, 0.9198, 0.8400, 0.1758],
        [0.7802, 0.1186, 0.7868, 0.9983, 0.6354, 0.5919, 0.3314],
        [0.8396, 0.2286, 0.6314, 0.1856, 0.5689, 0.4987, 0.2083],
        [0.0387, 0.6147, 0.3509, 0.2345, 0.0324, 0.9556, 0.1198]])

In [67]:
random_tensor.ndim

2

In [68]:
#create a random tensor with similar shape to an image tensor

random_image_size_tensor= torch.rand(size =(222,223, 8))#height, width,color channel
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([222, 223, 8]), 3)

In [69]:
random_image_size_tensor

tensor([[[0.9247, 0.0883, 0.7054,  ..., 0.1606, 0.6829, 0.3264],
         [0.4324, 0.4954, 0.5890,  ..., 0.6081, 0.2105, 0.0501],
         [0.9749, 0.3181, 0.2030,  ..., 0.1060, 0.5420, 0.5137],
         ...,
         [0.0397, 0.6865, 0.1200,  ..., 0.1122, 0.1850, 0.9912],
         [0.0685, 0.3535, 0.3672,  ..., 0.2338, 0.7852, 0.9629],
         [0.0152, 0.6124, 0.6980,  ..., 0.2143, 0.0706, 0.5554]],

        [[0.5517, 0.5852, 0.5777,  ..., 0.9564, 0.9864, 0.3880],
         [0.8660, 0.2576, 0.5356,  ..., 0.3357, 0.9225, 0.5887],
         [0.0669, 0.5661, 0.8964,  ..., 0.7709, 0.3521, 0.5678],
         ...,
         [0.2915, 0.8658, 0.3757,  ..., 0.1573, 0.8299, 0.9389],
         [0.6610, 0.2312, 0.1153,  ..., 0.3874, 0.4174, 0.2238],
         [0.8854, 0.2326, 0.1714,  ..., 0.7737, 0.3635, 0.2381]],

        [[0.3144, 0.9329, 0.1237,  ..., 0.7843, 0.1547, 0.9094],
         [0.7505, 0.6856, 0.4686,  ..., 0.8878, 0.5844, 0.6234],
         [0.5407, 0.3106, 0.2983,  ..., 0.2146, 0.9933, 0.

In [70]:
#create a tensor of all zeros

zeros = torch.zeros(size=(7, 7))
zeros

tensor([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]])

In [71]:
#create a tensor of all ones

ones= torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [72]:
#use torch.range
torch.range(0, 10)

<ipython-input-72-a089c3bf7207>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [73]:
one_to_ten= torch.arange(start=0, end= 10000, step=100)
one_to_ten

tensor([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000, 1100,
        1200, 1300, 1400, 1500, 1600, 1700, 1800, 1900, 2000, 2100, 2200, 2300,
        2400, 2500, 2600, 2700, 2800, 2900, 3000, 3100, 3200, 3300, 3400, 3500,
        3600, 3700, 3800, 3900, 4000, 4100, 4200, 4300, 4400, 4500, 4600, 4700,
        4800, 4900, 5000, 5100, 5200, 5300, 5400, 5500, 5600, 5700, 5800, 5900,
        6000, 6100, 6200, 6300, 6400, 6500, 6600, 6700, 6800, 6900, 7000, 7100,
        7200, 7300, 7400, 7500, 7600, 7700, 7800, 7900, 8000, 8100, 8200, 8300,
        8400, 8500, 8600, 8700, 8800, 8900, 9000, 9100, 9200, 9300, 9400, 9500,
        9600, 9700, 9800, 9900])

In [74]:
#creating tensors like

ten_zeros= torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0])

TENSOR DATATYPES

Note ❎Tensor datatypes are one of the 3 big issues you will run into with PyTorch and deep learning

1. Tensors not the right datatype
2. Tensors not the right shape
3. tensors not on the right devices

In [75]:
float_32_tensor= torch.tensor([3.0, 6.0, 7.0],
                              dtype=torch.float32,
                              device= None,
                              requires_grad=False
                              )

float_32_tensor

tensor([3., 6., 7.])

In [76]:
float_16_tensor= float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 7.], dtype=torch.float16)

In [77]:
float_32_tensor*float_16_tensor

tensor([ 9., 36., 49.])

In [78]:
int_32_tensor= torch.tensor([3, 6, 9],
                            dtype= torch.long)
int_32_tensor

tensor([3, 6, 9])

In [79]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 63.])

In [80]:
float_32_tensor.shape

torch.Size([3])

GETTING INFORMATION FROM TENSORS

In [81]:
some_tensor= torch.rand(5, 7)
some_tensor

tensor([[0.7799, 0.7949, 0.2040, 0.9860, 0.1874, 0.9595, 0.8192],
        [0.0076, 0.4184, 0.1784, 0.4318, 0.1959, 0.2680, 0.0543],
        [0.6932, 0.8864, 0.1083, 0.5740, 0.4398, 0.5184, 0.7587],
        [0.1432, 0.8250, 0.9688, 0.2923, 0.6198, 0.3368, 0.8917],
        [0.4138, 0.6851, 0.8725, 0.9201, 0.3806, 0.0110, 0.4440]])

In [82]:
print(some_tensor)
print(f"Datatype is {some_tensor.dtype}"  )
print(f"shape is {some_tensor.shape}" )
print(f"device is {some_tensor.device}" )



tensor([[0.7799, 0.7949, 0.2040, 0.9860, 0.1874, 0.9595, 0.8192],
        [0.0076, 0.4184, 0.1784, 0.4318, 0.1959, 0.2680, 0.0543],
        [0.6932, 0.8864, 0.1083, 0.5740, 0.4398, 0.5184, 0.7587],
        [0.1432, 0.8250, 0.9688, 0.2923, 0.6198, 0.3368, 0.8917],
        [0.4138, 0.6851, 0.8725, 0.9201, 0.3806, 0.0110, 0.4440]])
Datatype is torch.float32
shape is torch.Size([5, 7])
device is cpu


MANIPULATING TENSORS

one can multiply
divide
add
subtract
matrix multiplication

In [83]:
#create tensor

tensor= torch.tensor([7, 7, 8])
tensor+ 100

tensor([107, 107, 108])

In [84]:
tensor + 10

tensor([17, 17, 18])

In [85]:
tensor/2

tensor([3.5000, 3.5000, 4.0000])

In [86]:
tensor- 10

tensor([-3, -3, -2])

In [87]:
# using pytorch in built functions

print(torch.add(tensor, 20))
print(torch.mul(tensor, 2))
print(torch.sub(tensor, 2))
print(torch.div(tensor, 7))

tensor([27, 27, 28])
tensor([14, 14, 16])
tensor([5, 5, 6])
tensor([1.0000, 1.0000, 1.1429])


In [88]:
#MATRIX MULTIPLICATION/ dot product
print(tensor , "*", tensor)
print(f"equals: {tensor*tensor}")


tensor([7, 7, 8]) * tensor([7, 7, 8])
equals: tensor([49, 49, 64])


In [89]:
torch.matmul(tensor, tensor)

tensor(162)

One of the most common errors in deep learning: shape errors

In [90]:
#Shapes for matrix multiplication
tensor_A= torch.tensor([[1,4],
                       [7,7],
                       [8,9]])

tensor_B= torch.tensor([[1,8],
                        [8,0],
                        [9,8]])

torch.mm(tensor_A,tensor_B)

RuntimeError: ignored

In [91]:
tensor_B.shape , tensor_A.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

to fix the shape issues , we can multiply the shape of one of our tensors using a **transpose**

**Transpose **switches axis of one the tensors

In [92]:
tensor_A.T

tensor([[1, 7, 8],
        [4, 7, 9]])

In [93]:
torch.mm(tensor_A.T, tensor_B)

tensor([[129,  72],
        [141, 104]])

In [94]:
tensor_C=(tensor_B.T)
tensor_C.shape

torch.Size([2, 3])

TENSOR AGGREGATION

In [95]:
x=torch.arange(0, 1000, 100)
x

tensor([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [96]:
torch.min(x)
x.min()

tensor(0)

In [100]:
x.max()

tensor(900)

In [97]:
torch.mean(x.type(torch.float32))
x.type(torch.float32).mean()

tensor(450.)

In [99]:
x.sum()

tensor(4500)

In [98]:
 x.argmin()

tensor(0)

In [101]:
x.argmax()

tensor(9)


RESHAPING, STACKING, SQUEEZING & UNSQUEEZING TENSORS
> Reshaping:
Reshaping refers to changing the shape of a tensor while preserving the total number of elements. It allows you to reorganize the dimensions of a tensor. For example, you can reshape a 2D tensor into a 1D tensor or vice versa. Reshaping is commonly used when the input shape of a layer in a neural network does not match the desired shape, and you need to reshape the tensor to fit the layer's requirements.

Stacking:
Stacking involves combining multiple tensors along a new dimension. It is used to concatenate tensors together. For example, if you have two tensors of shape (3, 4) and you stack them along a new dimension, the resulting tensor will have the shape (2, 3, 4). Stacking is commonly used when you want to combine multiple samples or batches of data together.

Squeezing:
Squeezing is the operation of removing dimensions or axes with a size of 1 from a tensor. It reduces the rank (number of dimensions) of the tensor. For example, if you have a tensor of shape (1, 3, 1, 5), squeezing it will remove the dimensions with size 1, resulting in a tensor of shape (3, 5). Squeezing is useful when you want to remove unnecessary singleton dimensions and simplify the tensor's shape.

Unsqueezing:
Unsqueezing is the opposite operation of squeezing. It adds dimensions with a size of 1 to a tensor, increasing its rank. Unsqueezing allows you to insert singleton dimensions to match the expected shape for certain operations. For example, unsqueezing a tensor of shape (3, 5) along dimension 0 will result in a tensor of shape (1, 3, 5). Unsqueezing is commonly used when you want to broadcast a tensor across another tensor with a different shape.



In [102]:
#Create tensor

y= torch.arange(1., 10.)
y , y.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [106]:
y_reshaped= y.reshape(1, 9)
y_reshaped , y_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [107]:
z= y.view(1, 9)
z , z.shape

#a view of a tensor shares the same memory with the original tensor

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [110]:
#stack tensors on top of each other

y_stacked= torch.stack([y, y, y, y], dim=0)
y_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [115]:
#Squeezing and unsqueezing
print(f"previous tensor {y_reshaped}")
print(f"previous shape { y_reshaped.shape}")
print(f"new tensor { y_reshaped.squeeze()}")
print(f"{y_reshaped.squeeze().size()}")
print(f"{y_reshaped.unsqueeze(dim=0)}")

previous tensor tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
previous shape torch.Size([1, 9])
new tensor tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
torch.Size([9])
tensor([[[1., 2., 3., 4., 5., 6., 7., 8., 9.]]])


In [117]:
#torch.permute returns a  view of the original tensor input with its dimensions permuted
y_original = torch.rand(size=(224, 224, 3)) # height , width , colour channels

#Permutation
y_original_permuted= y_original.permute(2, 0, 1)#shifts axis 0-> 1, 1->2, 2->0

print(f"Previous shape {y_original.shape}")
print(f"new shape {y_original_permuted.shape}")

Previous shape torch.Size([224, 224, 3])
new shape torch.Size([3, 224, 224])
