<a href="https://colab.research.google.com/github/Fidel-Leanne/pyTorch/blob/master/pyTorchFundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

pyTorch intro

In [1]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

print(torch.__version__)

2.0.1+cu118


Introduction to Tensors:

Creating Tensors

In [2]:
# scalar

scalar= torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
#vector 

vector= torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#MATRIX
MATRIX = torch.tensor([[8 , 0],
                      [7, 9]])

MATRIX


tensor([[8, 0],
        [7, 9]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([8, 0])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
#TENSOR
TENSOR = torch.tensor([[[5, 9 ,7],
                        [7, 8, 0],
                        [8, 9, 9]]])

TENSOR

tensor([[[5, 9, 7],
         [7, 8, 0],
         [8, 9, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

Random Tensors

'start with random numbers -> look at data->update random numbers -> look at data- update random numbers

In [15]:
# create a random tensor

random_tensor = torch.rand(7, 7)
random_tensor

tensor([[0.8663, 0.9252, 0.1288, 0.1564, 0.4604, 0.2909, 0.0434],
        [0.4833, 0.3574, 0.7848, 0.6466, 0.1598, 0.1253, 0.2067],
        [0.1208, 0.7126, 0.8239, 0.9194, 0.5276, 0.7362, 0.5037],
        [0.4316, 0.8482, 0.5588, 0.7286, 0.3285, 0.8092, 0.4939],
        [0.3433, 0.8646, 0.8068, 0.7736, 0.2004, 0.0871, 0.8739],
        [0.4695, 0.6606, 0.5032, 0.0631, 0.3957, 0.3039, 0.9175],
        [0.0463, 0.4369, 0.1808, 0.3608, 0.9422, 0.6186, 0.8094]])

In [16]:
random_tensor.ndim

2

In [17]:
#create a random tensor with similar shape to an image tensor

random_image_size_tensor= torch.rand(size =(222,223, 8))#height, width,color channel
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([222, 223, 8]), 3)

In [18]:
random_image_size_tensor

tensor([[[0.5959, 0.8368, 0.6750,  ..., 0.9748, 0.4222, 0.2103],
         [0.8778, 0.3939, 0.9870,  ..., 0.7750, 0.9837, 0.3775],
         [0.6747, 0.9073, 0.4863,  ..., 0.0870, 0.9424, 0.9300],
         ...,
         [0.1772, 0.9316, 0.1274,  ..., 0.7589, 0.9756, 0.8515],
         [0.3355, 0.6557, 0.7446,  ..., 0.0788, 0.9970, 0.5394],
         [0.5982, 0.0197, 0.5673,  ..., 0.6851, 0.3836, 0.5595]],

        [[0.5175, 0.2275, 0.2737,  ..., 0.4784, 0.8364, 0.4812],
         [0.5699, 0.5272, 0.6864,  ..., 0.8687, 0.0180, 0.8389],
         [0.1389, 0.6871, 0.1633,  ..., 0.5319, 0.6988, 0.2952],
         ...,
         [0.2862, 0.6148, 0.8029,  ..., 0.2799, 0.8602, 0.1150],
         [0.8330, 0.0096, 0.6712,  ..., 0.4560, 0.0783, 0.3331],
         [0.9108, 0.1646, 0.5311,  ..., 0.8217, 0.1952, 0.8461]],

        [[0.2938, 0.8468, 0.5863,  ..., 0.1472, 0.9131, 0.1371],
         [0.9547, 0.2965, 0.7893,  ..., 0.0944, 0.2503, 0.4487],
         [0.1637, 0.6947, 0.3066,  ..., 0.4342, 0.3245, 0.

In [19]:
#create a tensor of all zeros

zeros = torch.zeros(size=(7, 7))
zeros

tensor([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]])

In [20]:
#create a tensor of all ones

ones= torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
#use torch.range
torch.range(0, 10)

<ipython-input-21-a089c3bf7207>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [22]:
one_to_ten= torch.arange(start=0, end= 10000, step=100)
one_to_ten

tensor([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000, 1100,
        1200, 1300, 1400, 1500, 1600, 1700, 1800, 1900, 2000, 2100, 2200, 2300,
        2400, 2500, 2600, 2700, 2800, 2900, 3000, 3100, 3200, 3300, 3400, 3500,
        3600, 3700, 3800, 3900, 4000, 4100, 4200, 4300, 4400, 4500, 4600, 4700,
        4800, 4900, 5000, 5100, 5200, 5300, 5400, 5500, 5600, 5700, 5800, 5900,
        6000, 6100, 6200, 6300, 6400, 6500, 6600, 6700, 6800, 6900, 7000, 7100,
        7200, 7300, 7400, 7500, 7600, 7700, 7800, 7900, 8000, 8100, 8200, 8300,
        8400, 8500, 8600, 8700, 8800, 8900, 9000, 9100, 9200, 9300, 9400, 9500,
        9600, 9700, 9800, 9900])

In [23]:
#creating tensors like

ten_zeros= torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0])

TENSOR DATATYPES

Note ❎Tensor datatypes are one of the 3 big issues you will run into with PyTorch and deep learning

1. Tensors not the right datatype
2. Tensors not the right shape
3. tensors not on the right devices

In [32]:
float_32_tensor= torch.tensor([3.0, 6.0, 7.0],
                              dtype=torch.float32,
                              device= None,
                              requires_grad=False
                              )

float_32_tensor

tensor([3., 6., 7.])

In [33]:
float_16_tensor= float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 7.], dtype=torch.float16)

In [34]:
float_32_tensor*float_16_tensor

tensor([ 9., 36., 49.])

In [35]:
int_32_tensor= torch.tensor([3, 6, 9],
                            dtype= torch.long)
int_32_tensor

tensor([3, 6, 9])

In [36]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 63.])

In [37]:
float_32_tensor.shape

torch.Size([3])